name: Automatic release

on:
  push:
    branches:
      - main

jobs:
  call-pre-commit:
    uses: geokrety/geokrety-gha-workflows/.github/workflows/release.yml@main
    with:
      GH_TOKEN: ${{ secrets.GH_TOKEN }}
